sudo : required
services:
    - docker

before_install:
    - docker build -t 32bharat/multi-docker -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true bharat/multi-docker npm test
after_success:
    - docker build -t 32bharat/mutli-client ./client
    - docker build -t 32bharat/multi-nginx ./nginx
    - docker build -t 32bharat/multi-server ./server
    - docker build -t 32bharat/multi-worker ./worker
#log in to Docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# take images and push them to Docker hub
    - docker push 32bharat/mutli-client
    - docker push 32bharat/multi-nginx
    - docker push 32bharat/multi-server
    - docker push 32bharat/multi-worker
